config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :skip => [:registrations]
  
  resources :beta_users, :except => [:index, :new]
   
  get 'users' => 'beta_users#index'

  get 'invite' => 'beta_users#new'
    

  root 'pages#index'

  get '/terms' => 'pages#terms'

  get '/privacy' => 'pages#privacy'

  get '/faq' => 'pages#faq'

  get '/contact' => 'pages#contact'

  get '/merchant' => 'pages#merchant'

  get '/buyer' => 'pages#buyer'

  get '/merchant_info' => 'pages#more'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]

          devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :username,
         presence: true,
         uniqueness: {
         	case_sensitive: false
         }

end

app/models/beta_user.rb
class BetaUser < ActiveRecord::Base

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	ROLE_OPTIONS = ["Designer/Brand", "Consumer"]


	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, 
			  uniqueness: { case_sensitive: false }, 
			  format: { with: VALID_EMAIL_REGEX }
	validates :role, presence: true

	def full_name
		"#{first_name} #{last_name}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	  def configure_permitted_parameters
	    	devise_parameter_sanitizer.for(:sign_up) do |u|
		      	u.permit(
		        :email, :password, :password_confirmation, :username
		      )
	   		end

	   	devise_parameter_sanitizer.for(:account_update) do |u|
      		u.permit(
      	:email, :password, :password_confirmation, :username
      	)
      	end
  end
end

app/controllers/beta_users_controller.rb
class BetaUsersController < ApplicationController
  before_action :authorize, only: [:index, :show, :update, :destroy]
  before_action :set_beta_user, only: [:edit, :update, :destroy]
  
  # GET /beta_users
  # GET /beta_users.json
  def index
    @beta_users = BetaUser.all
  end

  # GET /beta_users/1
  # GET /beta_users/1.json
  def show
  end

  # GET /beta_users/new
  def new
    @beta_user = BetaUser.new
  end

  # GET /beta_users/1/edit
  def edit
  end

  # POST /beta_users
  # POST /beta_users.json
  def create
    @beta_user = BetaUser.new(beta_user_params)

    respond_to do |format|
      if @beta_user.save
        format.html { redirect_to root_path, notice: "We'll be in touch shortly." }
        format.json { render :show, status: :created, location: @beta_user }
        UserNotifier.signup(@beta_user, @admin).deliver_now
        UserNotifier.thanks(@beta_user).deliver_now
      else
        format.html { render :new }
        format.json { render json: @beta_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beta_users/1
  # PATCH/PUT /beta_users/1.json
  def update
    respond_to do |format|
      if @beta_user.update(beta_user_params)
        format.html { redirect_to @beta_user, notice: 'Beta user was successfully updated.' }
        format.json { render :show, status: :ok, location: @beta_user }
      else
        format.html { render :edit }
        format.json { render json: @beta_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beta_users/1
  # DELETE /beta_users/1.json
  def destroy
    @beta_user.destroy
    respond_to do |format|
      format.html { redirect_to beta_users_url, notice: 'Beta user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beta_user
      @beta_user = BetaUser.find(params[:id])
    end

    def authorize
      unless current_admin
        flash[:alert] = 'Unauthorized'
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beta_user_params
      params.require(:beta_user).permit(:first_name, :last_name, :email, :role)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def index
	end

	def terms
	end

	def privacy
	end

	def buyer
	end

	def merchant
	end

	def contact
	end

	def FAQ
	end

	def more
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beta_users_helper.rb
module BetaUsersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/beta_users/_form.html.erb
<!DOCTYPE html>
<div class="brand_logo">
 <a href="/"><img class="masthead-brand center-block" src="/cropgrnblkexp2.png" style="max-height: 100px;">
</div></a>

<%= form_for(@beta_user) do |f| %>
  <% if @beta_user.errors.any? %>
    <div class="error_msg" style="margin-right:auto; margin-left:auto;">
      <div id="error_explanation">
        <h2><%= pluralize(@beta_user.errors.count, "error") %> prohibited your form being saved:</h2>

        <ul>
        <% @beta_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="form-group text-center">
      <h4 class="header"><strong>Cubey Private Beta Invite</strong></h4>
    </div>
    <div class="form-group text-center">Please complete the form to sign up for the Private Beta and a member of the team will get back to you ASAP
    </div>

    <div class="form text-center">
      <div class="form-group">
        <%= f.text_field :first_name, placeholder: "First Name" %>
      </div>
      <div class="form-group">
        <%= f.text_field :last_name, placeholder: "Last Name" %>
      </div>
      <div class="form-group">
        <%= f.text_field :email, placeholder: "Email (eg. john@example.com)" %>
      </div>
      <div class="form-group">
        <%= f.label :role, class: "role_label" %><br>
        <%=  f.select :role, BetaUser::ROLE_OPTIONS, prompt: "Please select" %>
      </div>
      <div class="form-group actions">
        <%= f.submit "Sign up", class: "btn btn_learn" %>
      </div>
    </div>
<% end %>

app/views/beta_users/edit.html.erb
<h1>Editing Beta User</h1>

<%= render 'form' %>

<%= link_to 'Show', @beta_user %> |
<%= link_to 'Back', beta_users_path %>

app/views/beta_users/index.html.erb
<h2 class="header text-center">Beta Users</h2><br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <h5 class="title"><span>Name</span> <span class="email">Email</span> <span>Role</span></h5>
    <% @beta_users.each_with_index do |beta_user, i| %>
    <div class="deets">
      <ol>
          <%= i += 1 %>
          <%= beta_user.full_name %> 
          <%= beta_user.email %>
          <%= beta_user.role %>

          <%= link_to 'Show', beta_user %>
          <%= link_to 'Edit', edit_beta_user_path(beta_user) %>
          <%= link_to 'Destroy', beta_user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </ol>
    </div>
    <% end %>
  </tbody>
</table>

<br>

<div class="text-center">
<%= link_to 'New Beta user', invite_path, class: "btn btn_learn" %>
</div>

app/views/beta_users/new.html.erb
<%= render 'form' %>

app/views/beta_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_beta_user_path(@beta_user) %> |
<%= link_to 'Back', beta_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  	<title>Cubey Beta</title>
  	
     <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<!-- font -->
	 <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400' rel='stylesheet' type='text/css'>

  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74843621-1', 'auto');
  ga('send', 'pageview');

  </script>

</head>
<body>

    <div class="navbar-text pull-right">

      <% if admin_signed_in? %>

      Logged in as <strong><%= current_admin.username %></strong> |
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>

    <% end %>
    </div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

<%= yield %>
	

</body>
</html>

app/views/pages/contact.html.erb
<div class="jumbotron text-center contact" style="max-height:100%; max-width:100%; padding-top: 250px; padding-bottom: 300px;">
	<h1 class="text-center contact">Contact</h1><br>
	<h4>Reach us at:</h4>
	<p><a href="mailto:info@cubey.co">info@cubey.co</a></p>
	<p class="soc_media"><a href="http://twitter.com/cubeyHQ" class="icon-twitter"><img src="twitter.png" style="max-height: 30px;"></a> 
       <a href="https://instagram.com/cubeyHQ" class="icon-instagram"><img src="instagram.png" style="max-height: 25px;"></a>
   </p>
</div>

app/views/pages/faq.html.erb
<div class="jumbotron faqs text-center" style="max-height: 100%; width:100%; padding-top: 250px; padding-bottom: 300px;">
<h1 class="text-center">FAQs</h1>
<h3>We haven't got any yet. Why don't you ask us some?</h3>
<p>info@cubey.co</p>
</div>

app/views/pages/index.html.erb
      <div class="rowzer">
				<div class="masthead clearfix">
					<div class="inner">
						<img class="masthead-brand center-block" src="cropgreenbexp2.png" style="max-height: 100px;">
					</div>
        </div>

        <div class="inner">
        <div><a class="pull-right become btn btn-apply" href="https://www.cubey.co/apply">SELL WITH US</a></div>
          <h2 class="heading text-center care">Connecting you to <span class="type-text"></span> designers..</h2>
          <h4 class="lead text-center">Opportunity to get one-off and discounted pieces</h4>
        </div>
      </div>

      <div class="partners">
            <div class="container">
              <div class="row meet">
                <h4 class="text-center">Meet some of our featured brands</h4>
                <div class="text-center col-xs-3 col-sm-3 col-md-3 fir">
                  <a class="part" href="https://www.cubey.co/sabanovamadara">
                    <img class="img-rounded circa" src="/madara.jpg">
                  </a>
                </div>

                <div class="col-xs-3 col-sm-3 col-md-3 sec">
                  <a class="part" href="https://www.cubey.co/joetaylor">
                    <img class="img-rounded circa" src="/jt.png">
                  </a>
                </div>

                <div class="col-xs-3 col-sm-3 col-md-3 third">
                  <a class="part" href="https://www.cubey.co/aliceelizabeth">
                    <img class="img-rounded circa" src="/ae.png">
                  </a>
                </div> 

                <div class="col-xs-3 col-sm-3 col-md-3 fourth">
                  <a class="part" href="https://www.cubey.co/asdesigns">
                    <img class="img-rounded circa" src="/asd2.jpg">
                  </a>
                </div>

                <div class="text-center col-xs-3 col-sm-3 col-md-3">
                  <a class="part" href="https://www.cubey.co/judtlv">
                    <img class="img-rounded circa" src="/jud3.jpg">
                  </a>
                </div> 

                 <div class="text-center col-xs-3 col-sm-3 col-md-3 sec">
                  <a class="part" href="https://www.cubey.co/a-mm-e">
                    <img class="img-rounded circa" src="/amm2.jpg">
                  </a>
                </div> 

                  <div class="text-center col-xs-3 col-sm-3 col-md-3">
                  <a class="part" href="https://www.cubey.co/cubey">
                    <img class="img-rounded circa" src="/cubeyshop.png">
                  </a>
                </div> 

              </div>
            </div>
          </div> 

          <div class="home-works">
            <div class="container">
              <div class="row text-center">
                <h2 class="text-center">How it Works</h2>
                <div class="col-md-4" style="margin-right:0; margin-left:0;">
                  <div class="content text-center">
                    <div class="header">
                      <img src="1.png" style="max-height: 60px;">
                    </div>
                    <h4>There's something for everybody</h4><br>
                    <strong><p>Browse through our list of well curated fashion-forward brands 
                      and find the perfect bargain for the style you are after.</p></strong>
                  </div>
                </div>
                <div class="col-md-4" style="margin-right:0; margin-left:0;">
                  <div class="content text-center">
                    <div class="header">
                      <img src="2.png" style="max-height: 60px;">
                    </div>
                    <h4>We celebrate independent fashion brands</h4><br>
                   <strong><p>Our partner brands offer discounts of up to 75%
                      off or shop one of our brands with one-off pieces. In the process, you also discover 
                      new and exciting indie brands. </p></strong>
                  </div>
                </div>
                <div class="col-md-4" style="margin-right:0; margin-left:0;">
                  <div class="content text-center">
                    <div class="header">
                      <img src="3.png" style="max-height: 60px;">
                    </div>
                    <h4>Add To Cart</h4><br>
                   <strong><p>Take that leap and try a new brand! 
                      You're supporting independent designers trying 
                      to make it in the fashion industry, so why not buy that 
                      item none of your mates have!</p></strong>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="vision">
            <div class="row cover">
              <div class="cover-container">
               <!-- <img class="vish" src="vision2.jpg"> -->
                <h1 class="heading text-center vishtxt">Our Vision</h1><br>
                <h2 class="lead text-center">To create a community of the most directional fashion brands</h2>
              </div>
            </div>
          </div>

          

          <div class="learn_more site-wrapper-inner" style="height: 400px; width:100%;">
            <div class="container">
              <div class="row text-center">
                <h2 class="brnd">Are you a brand/designer and you want to find out if Cubey is for you?</h2>
                <div class="col-xs-4-offset col-sm-4-offset col-md-4-offset">
                  <a href="/merchant_info" class="btn btn_learn">Learn more</a>
                </div>
              </div>
            </div>
          </div>


  
  <footer class="footer" style="height: 250px; width: 100%;">
    <div class="container">
      <div class="row mastfoot">
        <div class="col-xs-4 col-sm-4 col-md-4 inner text-left" style="margin-right:0; margin-left:0;">
          <h5>FOLLOW US</h5> 
          <div class="soc_media">
            <p><a href="https://twitter.com/cubeyHQ" class="icon-twitter"><img src="twitter.png" style="max-height: 25px;"></a> 
              <a href="https://instagram.com/cubeyHQ" class="icon-instagram"><img src="instagram.png" style="max-height: 20px;"></a></p>
          </div>
          <p>&copy; Copyright Cubey Ltd. 2016, all rights reserved.</p>
          <p>Cubey Ltd is registered and incorporated in England and Wales, company registration number 09822905.</p>
        </div>
        
        <div class="col-xs-4 col-sm-4 col-md-4 text-left legal" style="margin-right:0; margin-left:0;">
          <h5>LEGAL</h5>
          <p><a href="/terms">Terms</a></p>
          <p><a href="/privacy">Privacy Policy</a></p>
          <p><a href="/buyer">Buyer Agreement</a></p>
          <p><a href="/merchant">Merchant Agreement</a></p>
        </div>
        
        <div class="col-xs-4 col-sm-4 col-md-4 text-left other" style="margin-right:0; margin-left:0;">
          <h5>OTHER</h5>
          <p><a href="/faq">FAQs</a></p>
          <p><a href="/contact">Contact</a></p>
        </div>
      </div>
    </div>
  </footer>

  <script src="jquery.js"></script>
  <script src="jquery.teletype.js"></script>

app/views/pages/more.html.erb
<!DOCTYPE html>
<html>
	<div class="more">
		<div class="inner">
			<a href="/"><img class="masthead-brand center-block" src="/cropwhtexp.png" style="max-height: 100px;"></a>
			<div class="slider">
			
				<div class="slide active-slide info jumbotron" style="height: auto; max-width: 100%; padding-bottom:0;">
					<div class="container">
						<div class="row text-center">
							<div class="slide-copy lead unsold">
								<h1>Clear your backlog of unsold stock</h1>
								<hr>
								<div class="lead_info center-block" style="max-width:900px;">
									<h5 class="lead">At Cubey, we want to help you clear your excess stock.
									We want customers to discover your amazing brand at reasonable prices.
									Do you have items from previous collections you would like to sell?
									Everything must go... at a <span class="light">discount</span> ofcourse!</h5>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="slide slide-feature back" style="height: auto; max-width: 100%; padding-bottom:100px;">
					<div class="container">
						<div class="row value" >
							<div class="slide-copy col-md-6 ico" style="max-width: 400px; margin-right:auto; margin-left:auto;">
								<div class="slide-img">
									<img class="lazy center-block" src="/sup2.png" style="max-height: 60px;">
								</div>
								<h4>We handle customer support for you, so you don't have to worry about dealing with customers, we'll deal with all customer requests on your behalf</h4>
							</div>

							<div class="slide-copy col-md-6 ico pull-right" style="max-width: 400px; margin-right:auto; margin-left:auto;">
								<div class="slide-img">
									<img class="lazy center-block" src="/inc2.png" style="max-height: 60px;">
								</div>
								<h4>Cubey generates additional income for you whether you sell 10 or 100 items a day. So brands of any size are welcome to join us</h4>
							</div>

							

							<br><br> <br>
							<div class="slide-copy col-md-6 ico pull-right disc bot" style="max-width: 400px; margin-right:auto; margin-left:auto;">
								<div class="slide-img">
									<img class="lazy center-block" src="/disc.png" style="max-height: 60px;">
								</div>
								<h4>New customers can discover your brand while shopping for bargains. Cubey serves as a discovery tool </h4>
							</div>

							<div class="slide-copy col-md-6 ico alert bot" style="max-width: 400px; margin-right:auto; margin-left:auto;">
								<div class="slide-img">
									<img class="lazy center-block" src="/notif.png" style="max-height: 60px;">
								</div>
								<h4>We alert you after each transaction to take the necessary steps to deliver to the customer as well as when stock levels are low, so you don't have to worry about inventory levels</h4>
							</div>

							<div class="join text-center ico">
								<a href="/invite" role="button" class="btn btn_more">Join the Private Beta</a>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="slider-nav navbar">
	      <a href="#" class="arrow-prev"><img src="/arrow-prev.png"></a>
	      <ul class="slider-dots">
	        <li class="dot active-dot">&bull;</li>
	        <li class="dot">&bull;</li>
	      </ul>
	      <a href="#" class="arrow-next"><img src="/arrow-next.png"></a>
	      <hr>
	</div> 

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="application.js"></script>
</html>

app/views/pages/thanks.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="thanks" style="height: 100%; width: 100%;">

</div>
</html>

app/views/user_notifier/signup.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	 <style type="text/css" media="screen">
      img.brand { 
      	max-height: 80px;
      	margin-left: auto;
      	margin-right: auto; 
      }
    </style>
</head>
<body>

<%= image_tag "http://beta.cubey.co/images/cropgrnblkexp2.png", class: "brand text-center" %>
<br><br>
<p>Howdy <%= @admin.username %>,</p>
<br>

<p>A new user has signed up, please try and send them an invitation to the platform as soon as you can.</p>

<p>The new user's name is: <%= @beta_user.first_name %> <%= @beta_user.last_name %><br> email address is: <%= @beta_user.email %></p>

<p>Regards,</p>
<p>Management</p>
<p>Cubey</p>

</body>
</html>

app/views/user_notifier/thanks.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	 <style type="text/css" media="screen">
      img.brand { 
      	max-height: 80px;
      	margin-left: auto;
      	margin-right: auto; 
      }
    </style>
</head>
<body>

<%= image_tag "http://beta.cubey.co/images/cropgrnblkexp2.png", class: "brand text-center" %>
<br><br>
<p>Howdy <%= @beta_user.first_name %>,</p>
<br>
<p>Thanks for signing up to Cubey.</p>
<p>Someone would be in touch shortly.</p>

<p>Best wishes,</p>
<br>
<p>Dapo Thomas</p>
<p>Founder/CEO</p>

</body>
</html>